# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bsplinefit <- function(xmat, y, degree, smoothing, alpha, knotspacing) {
    .Call('splinter_bsplinefit', PACKAGE = 'splinter', xmat, y, degree, smoothing, alpha, knotspacing)
}

bsplinepredict <- function(model, xmat) {
    .Call('splinter_bsplinepredict', PACKAGE = 'splinter', model, xmat)
}

